language: generic
dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
    - ccache
    - cmake
    - swig
    - libxkbcommon-x11-0
    - libglu1-mesa-dev
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-xinerama0
    
env:
  global:
    - INSTALL_EDM_VERSION=2.0.0
      PYTHONUNBUFFERED="1"
      QT_DEBUG_PLUGINS="1"

matrix:
  include:
  - env: RUNTIME=3.6 TOOLKITS="null pyqt pyqt5 pyside2"
  - os : osx
    env: RUNTIME=3.6 TOOLKITS="null pyqt pyqt5 pyside2"
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then
       ccache -s;
       ./ci/install-edm-linux.sh;
       export PATH="${HOME}/edm/bin:/usr/lib/ccache:${PATH}";
    else
       ./ci/install-edm-osx.sh;
       export PATH="${PATH}:/usr/local/bin";
    fi

  - edm install -y wheel click coverage
install:
  - for toolkit in ${TOOLKITS}; do
        if [[ ${TRAVIS_EVENT_TYPE} == "cron" ]] ; then
          edm run -- python ci/edmtool.py install --runtime=${RUNTIME} --toolkit=${toolkit} --source || exit;
        else
          edm run -- python ci/edmtool.py install --runtime=${RUNTIME} --toolkit=${toolkit} || exit;
        fi;
    done
script:
  - for toolkit in ${TOOLKITS}; do edm run -- python ci/edmtool.py test --runtime=${RUNTIME} --toolkit=${toolkit} || exit; done

after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
