language: python
python:
  - 2.7
  - 2.6
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy swig
  - source .travis_before_install
install:
  - pip install cython
  - pip install coveralls
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ETS_TOOLKIT='qt4' coverage run -p -m nose.core -v chaco; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ETS_TOOLKIT='wx' coverage run -p -m nose.core -v chaco; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage combine; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run -m nose.core -v chaco/tests; fi
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
