language: generic

addons:
  apt:
    packages:
    - ccache
    - cmake
    - swig

env:
  global:
    - INSTALL_EDM_VERSION=1.11.0
      PYTHONUNBUFFERED="1"

matrix:
  include:
  - env: RUNTIME=2.7 TOOLKIT=wx
  - os : osx
    env: RUNTIME=2.7 TOOLKIT=wx
  - env: RUNTIME=2.7 TOOLKIT=pyqt
  - os : osx
    env: RUNTIME=2.7 TOOLKIT=pyqt
  - env: RUNTIME=2.7 TOOLKIT=null
  - os : osx
    env: RUNTIME=2.7 TOOLKIT=null
  - env: RUNTIME=2.7 TOOLKIT=pyside
  - os : osx
    env: RUNTIME=2.7 TOOLKIT=pyside
  - env: RUNTIME=3.5 TOOLKIT=pyqt
  - os : osx
    env: RUNTIME=3.5 TOOLKIT=pyqt
  - env: RUNTIME=3.5 TOOLKIT=null
  - os : osx
    env: RUNTIME=3.5 TOOLKIT=null
  - env: RUNTIME=3.6 TOOLKIT=pyqt
  - os : osx
    env: RUNTIME=3.6 TOOLKIT=pyqt
  - env: RUNTIME=3.6 TOOLKIT=null
  - os : osx
    env: RUNTIME=3.6 TOOLKIT=null
  allow_failures:
    - os: osx
      env: RUNTIME=2.7 TOOLKIT=wx
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then
       export DISPLAY=:99.0;
       ccache -s;
       sh -e /etc/init.d/xvfb start;
       ./ci/install-edm-linux.sh;
       export PATH="${HOME}/edm/bin:/usr/lib/ccache:${PATH}";
    else
       ./ci/install-edm-osx.sh;
       export PATH="${PATH}:/usr/local/bin";
    fi

  - edm install -y wheel click coverage
install:
  - edm run -- python ci/edmtool.py install --runtime=${RUNTIME} --toolkit=${TOOLKIT} 
script:
  - edm run -- python ci/edmtool.py test --runtime=${RUNTIME} --toolkit=${TOOLKIT}

after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
