language: generic
dist: xenial
services:
  - xvfb

addons:
  apt:
    packages:
    - ccache
    - cmake
    - swig
    - libglu1-mesa

env:
  global:
    - INSTALL_EDM_VERSION=1.11.0
      PYTHONUNBUFFERED="1"

matrix:
  include:
  - env: RUNTIME=2.7 TOOLKITS="null pyqt pyside wx"
  - os : osx
    env: RUNTIME=2.7 TOOLKITS="null pyqt pyside wx"
  - env: RUNTIME=3.5 TOOLKITS="null pyqt"
  - os : osx
    env: RUNTIME=3.5 TOOLKITS="null pyqt"
  - env: RUNTIME=3.6 TOOLKITS="null pyqt"
  - os : osx
    env: RUNTIME=3.6 TOOLKITS="null pyqt"
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then
       ccache -s;
       ./ci/install-edm-linux.sh;
       export PATH="${HOME}/edm/bin:/usr/lib/ccache:${PATH}";
    else
       ./ci/install-edm-osx.sh;
       export PATH="${PATH}:/usr/local/bin";
    fi

  - edm install -y wheel click coverage
install:
  - for toolkit in ${TOOLKITS}; do edm run -- python ci/edmtool.py install --runtime=${RUNTIME} --toolkit=${toolkit} || exit; done
script:
  - for toolkit in ${TOOLKITS}; do edm run -- python ci/edmtool.py test --runtime=${RUNTIME} --toolkit=${toolkit} || exit; done

after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
