# This workflow targets stable released dependencies from EDM.
# Note that some packages may not actually be installed from EDM but from
# PyPI, see ci/edmtool.py implementations.

name: Test with EDM on Python 3.11

on: pull_request

env:
  INSTALL_EDM_VERSION: 3.5.0

jobs:

  # Test against EDM packages on Linux
  test-edm-linux-311:
    strategy:
      matrix:
        toolkit: ['null', 'pyside6']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install libegl1
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libglu1-mesa-dev
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0
          sudo apt-get install libxcb-shape0
          # Needed to work around https://bugreports.qt.io/browse/PYSIDE-1547
          sudo apt-get install libopengl0
        if: matrix.toolkit != 'null'
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-3.11-${{ matrix.toolkit }}-${{ hashFiles('ci/edmtool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python ci/edmtool.py install --runtime=3.11 --toolkit=${{ matrix.toolkit }}
      - name: Flake8
        run: edm run -- python ci/edmtool.py flake8 --runtime=3.11 --toolkit=${{ matrix.toolkit }}
        if: matrix.toolkit == 'null'
      - name: Run tests
        run: xvfb-run --server-args="-screen 0 1024x768x24" edm run -- python ci/edmtool.py test --runtime=3.11 --toolkit=${{ matrix.toolkit }}

  # Test against EDM packages on Windows and OSX
  test-with-edm-38:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        toolkit: ['null', 'pyside6']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-3.11-${{ matrix.toolkit }}-${{ hashFiles('ci/edmtool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python ci/edmtool.py install --runtime=3.11 --toolkit=${{ matrix.toolkit }}
      - name: Run tests
        run: edm run -- python ci/edmtool.py test --runtime=3.11 --toolkit=${{ matrix.toolkit }}
